interface_branding: ""
timeout: 5

term_font: boot():/terminus-font.bin
term_font_size: 8x16
term_margin: 64
term_margin_gradient: 4

wallpaper: boot():/wallpaper.bmp
wallpaper_style: stretched

term_palette: 24273a;ed8796;a6da95;eed49f;8aadf4;f5bde6;8bd5ca;cad3f5
term_palette_bright: 5b6078;ed8796;a6da95;eed49f;8aadf4;f5bde6;8bd5ca;cad3f5
term_background: 80000000
term_foreground: cad3f5
term_background_bright: 5b6078
term_foreground_bright: cad3f5

/Artix Linux
    protocol: linux
    kernel_path: boot():/vmlinuz-linux-cachyos-bore
    initrd_path: boot():/initramfs-linux-cachyos-bore.img
    cmdline: root=/dev/sda2 rootflags=subvol=@ rw quiet
