[main]
font=Terminess Nerd Font:weight=medium:size=11
font-bold=Terminess Nerd Font:weight=bold:size=11
font-italic=Terminess Nerd Font:weight=medium:slant=italic:size=11
font-bold-italic=Terminess Nerd Font:weight=bold:slant=italic:size=11
dpi-aware=yes
# gamma-correct-blending=yes   # NO activar aún: Swayfx no implementa wp-color-management y foot lo desactiva con warning
shell=/usr/bin/fish
pad=10x10
include=~/.cache/wal/colors-foot.conf

[colors-dark]
alpha=0.85
