[main]
font=Terminess Nerd Font:weight=medium:size=11
font-bold=Terminess Nerd Font:weight=bold:size=11
font-italic=Terminess Nerd Font:weight=medium:slant=italic:size=11
font-bold-italic=Terminess Nerd Font:weight=bold:slant=italic:size=11
dpi-aware=yes
# gamma-correct-blending=yes
shell=/usr/bin/fish
pad=10x10
include=~/.cache/wal/colors-foot.conf
