# : Manager [[[

[mgr]
cwd = { fg = "#dde4e4" }

# Find
find_keyword  = { fg = "#fff0d1", bold = true, italic = true, underline = true }
find_position = { fg = "#fff0d1", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#c6fbff", bg = "#c6fbff" }
marker_cut      = { fg = "#9bd0d4", bg = "#9bd0d4" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#fff0d1", bg = "#fff0d1" }

# Count
count_copied   = { fg = "#00373a", bg = "#c6fbff" }
count_cut      = { fg = "#00373a", bg = "#9bd0d4" }
count_selected = { fg = "#3e2e00", bg = "#fff0d1" }

# Border
border_symbol = "│"
border_style  = { fg = "#859394" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "", close = "" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#c6fbff", bold = true, bg = "#0e1515" }
inactive  = { fg = "#bac9ca", bg = "#0e1515" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#c6fbff", fg = "#00373a", bold = true }
normal_alt  = { bg = "#3b494a", fg = "#bac9ca" }

# Select mode
select_main = { bg = "#9bd0d4", fg = "#00373a", bold = true }
select_alt  = { bg = "#3b494a", fg = "#bac9ca" }

# Unset mode
unset_main = { bg = "#fff0d1", fg = "#3e2e00", bold = true }
unset_alt  = { bg = "#3b494a", fg = "#bac9ca" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_type  = { fg = "#fff0d1" }
perm_write = { fg = "#c6fbff" }
perm_read  = { fg = "#ffb4ab" }
perm_exec  = { fg = "#9bd0d4" }
perm_sep   = { fg = "#859394" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#c6fbff", bg = "#3b494a" }
progress_error  = { fg = "#ffb4ab", bg = "#3b494a" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3b494a" }
cand = { fg = "#c6fbff" }
rest = { fg = "#00474b" }
desc = { fg = "#dde4e4" }
separator = " ▶ "
separator_style = { fg = "#dde4e4" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#9bd0d4" }
title_warn  = { fg = "#fff0d1" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#859394" }
active = { fg = "#c6fbff", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#859394" }
value  = { fg = "#dde4e4" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#859394", bg = "#0e1515" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#859394" }
title   = {}
hovered = { fg = "#c6fbff", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#dde4e4" }
run    = { fg = "#dde4e4" }
footer = { fg = "#00373a", bg = "#9bd0d4" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#fff0d1" },

    # Media
    { mime = "{audio,video}/*", fg = "#9bd0d4" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ffb4ab" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#c6fbff" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffb4ab" },

    # Fallback
    { url = "*", fg = "#dde4e4" },
    { url = "*/", fg = "#c6fbff" },
]

# : ]]]
