# : Manager [[[

[mgr]
cwd = { fg = "#e3e2e4" }

# Find
find_keyword  = { fg = "#f1c591", bold = true, italic = true, underline = true }
find_position = { fg = "#f1c591", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#b2d0ee", bg = "#b2d0ee" }
marker_cut      = { fg = "#bdc8d5", bg = "#bdc8d5" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f1c591", bg = "#f1c591" }

# Count
count_copied   = { fg = "#13334b", bg = "#b2d0ee" }
count_cut      = { fg = "#27313c", bg = "#bdc8d5" }
count_selected = { fg = "#452b04", bg = "#f1c591" }

# Border
border_symbol = "│"
border_style  = { fg = "#8d9197" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "", close = "" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#b2d0ee", bold = true, bg = "#121315" }
inactive  = { fg = "#c3c7cd", bg = "#121315" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#b2d0ee", fg = "#13334b", bold = true }
normal_alt  = { bg = "#43474d", fg = "#c3c7cd" }

# Select mode
select_main = { bg = "#bdc8d5", fg = "#27313c", bold = true }
select_alt  = { bg = "#43474d", fg = "#c3c7cd" }

# Unset mode
unset_main = { bg = "#f1c591", fg = "#452b04", bold = true }
unset_alt  = { bg = "#43474d", fg = "#c3c7cd" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Permissions
perm_type  = { fg = "#f1c591" }
perm_write = { fg = "#b2d0ee" }
perm_read  = { fg = "#ffb4ab" }
perm_exec  = { fg = "#bdc8d5" }
perm_sep   = { fg = "#8d9197" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#b2d0ee", bg = "#43474d" }
progress_error  = { fg = "#ffb4ab", bg = "#43474d" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#43474d" }
cand = { fg = "#b2d0ee" }
rest = { fg = "#052840" }
desc = { fg = "#e3e2e4" }
separator = " ▶ "
separator_style = { fg = "#e3e2e4" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#bdc8d5" }
title_warn  = { fg = "#f1c591" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#8d9197" }
active = { fg = "#b2d0ee", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#8d9197" }
value  = { fg = "#e3e2e4" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#8d9197", bg = "#121315" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#8d9197" }
title   = {}
hovered = { fg = "#b2d0ee", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#e3e2e4" }
run    = { fg = "#e3e2e4" }
footer = { fg = "#27313c", bg = "#bdc8d5" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#f1c591" },

    # Media
    { mime = "{audio,video}/*", fg = "#bdc8d5" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#ffb4ab" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#b2d0ee" },

    # Special files
    { url = "*", is = "orphan", bg = "#93000a" },
    { url = "*", is = "exec", fg = "#ffb4ab" },

    # Fallback
    { url = "*", fg = "#e3e2e4" },
    { url = "*/", fg = "#b2d0ee" },
]

# : ]]]
