[colors-dark]
foreground={{ colors.on_surface.default.hex | replace: "#", "" }}
background={{ colors.surface_dim.default.hex | replace: "#", "" }}
cursor={{ colors.surface_dim.default.hex | replace: "#", "" }} {{ colors.primary.default.hex | replace: "#", "" }}

regular0={{ colors.surface_dim.default.hex | replace: "#", "" }}
regular1={{ colors.error.default.hex | replace: "#", "" }}
regular2={{ colors.tertiary_fixed_dim.default.hex | replace: "#", "" }}
regular3={{ colors.primary_fixed_dim.default.hex | replace: "#", "" }}
regular4={{ colors.secondary_fixed_dim.default.hex | replace: "#", "" }}
regular5={{ colors.on_surface_variant.default.hex | replace: "#", "" }}
regular6={{ colors.outline.default.hex | replace: "#", "" }}
regular7={{ colors.on_surface.default.hex | replace: "#", "" }}
bright0={{ colors.surface_variant.default.hex | replace: "#", "" }}
bright1={{ colors.error.default.hex | replace: "#", "" }}
bright2={{ colors.tertiary_fixed.default.hex | replace: "#", "" }}
bright3={{ colors.primary_fixed.default.hex | replace: "#", "" }}
bright4={{ colors.secondary_fixed.default.hex | replace: "#", "" }}
bright5={{ colors.on_surface.default.hex | replace: "#", "" }}
bright6={{ colors.on_surface_variant.default.hex | replace: "#", "" }}
bright7={{ colors.on_surface.default.hex | replace: "#", "" }}
