# Shell variables
# Generated by 'matugen'
wallpaper='{{image}}'

# Special
background='{{colors.surface_dim.default.hex_stripped}}'
foreground='{{colors.on_surface.default.hex_stripped}}'
cursor='{{colors.primary.default.hex_stripped}}'

# Colors
color0='{{colors.surface_dim.default.hex_stripped}}'
color1='{{colors.error.default.hex_stripped}}'
color2='{{colors.tertiary_fixed_dim.default.hex_stripped}}'
color3='{{colors.primary_fixed_dim.default.hex_stripped}}'
color4='{{colors.secondary_fixed_dim.default.hex_stripped}}'
color5='{{colors.on_surface_variant.default.hex_stripped}}'
color6='{{colors.outline.default.hex_stripped}}'
color7='{{colors.on_surface.default.hex_stripped}}'
color8='{{colors.surface_variant.default.hex_stripped}}'
color9='{{colors.error.default.hex_stripped}}'
color10='{{colors.tertiary_fixed.default.hex_stripped}}'
color11='{{colors.primary_fixed.default.hex_stripped}}'
color12='{{colors.secondary_fixed.default.hex_stripped}}'
color13='{{colors.on_surface.default.hex_stripped}}'
color14='{{colors.on_surface_variant.default.hex_stripped}}'
color15='{{colors.on_surface.default.hex_stripped}}'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
