-- Generated by Matugen

require('base16-colorscheme').setup({
  base00 = "#111414",
  base01 = "#0b0f0f",
  base02 = "#191c1c",
  base03 = "#3f4849",
  base04 = "#bfc8c8",
  base05 = "#e1e3e2",
  base06 = "#2e3131",
  base07 = "#363a3a",

  base08 = "#fda67a",
  base09 = "#fdb793",
  base0A = "#b2cbcc",
  base0B = "#92d1d4",
  base0C = "#c18262",
  base0D = "#5b9b9e",
  base0E = "#344b4c",
  base0F = "#93b6b8",
})

vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#5b9b9e',
  fg = '#000000',
})

local function set_hl(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

set_hl({ 'String', 'TSString' }, {
  fg = '#fc8548',
})

set_hl({ 'TSComment', 'Comment' }, {
  fg = '#899393',
  italic = true,
})

set_hl({ 'TSMethod', 'Method' }, {
  fg = '#fdb793',
})

set_hl({ 'TSFunction', 'Function' }, {
  fg = '#b2cbcc',
})

set_hl({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
  fg = '#24686b',
})
